### ISSUE TITLE
Spam and extreme lag [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [codeHusky/HuskyCrates-Sponge#59]
Hi.
Basically your mod throws a lot of spam on the console and generates a lot of lag on the server.
I have sent you the log file for your review, you could have some incompatibility with the mod headcrumbs.
I am looking forward to your response
regards!

Modpack: SkyFactory 3 (v3.0.15)
Sponge: spongeforge-1.10.2-2477-5.2.0-BETA-2691.jar
HuskyCrates-v1.7.2.jar
HuskyUI-v0.3.1.jar
LuckPerms-Sponge-3.4.20.jar

https://pastebin.com/raw/3WX9xtWY

**Comment by SubtypeZero** [comment]
What makes you think this has anything to do with HuskyCrates?

**Comment by HeberonYT** [comment]
Well I'm not an expert analyzing these files, but much of the spam contains information related to the mod.
I only hope the author tells me if its operation is normal or it is an incompatibility.

![screenshot_3](https://user-images.githubusercontent.com/13698597/31909761-c381b856-b800-11e7-9332-489ee5621336.png)

**Comment by SubtypeZero** [comment]
That's most likely an issue with your database configuration. Either way, that highlighted bit is debug information, so I wouldn't worry about it unless you know that it's actually causing problems. As for your lag problems, I would suggest getting a tick profiler to see what the cause is before blaming any particular plugin or mod. Sky Factory 3 has a bunch of problems on it's own and you may need to ask players to avoid doing certain things with the mods or ban troublesome items.

**Comment by codeHusky** [comment]
Until you can conclusively determine that my very lightweight plugin is lagging your server, this issue will be closed.
