### ISSUE TITLE
Cooldown Expiration doesn't persist through server reboots.

### ISSUE THREAD

**Issue by KhaozFrost** [codeHusky/HuskyCrates-Sponge#62]
Currently I don't see a point in why cooldowns are a thing for free crates if they aren't implemented correctly. Upon server restart/reloading I think cooldowns need to be persistant. So some fixes need to be made with the database to make this 100x better.

**Comment by codeHusky** [comment]
Normally, a cooldown shouldn't extend past a server restart as that really wasn't the intended purpose of the cooldown feature. It'll certainly be moving to database reliance, but one of the other reasons why that wasn't done in the first place was because the current database management system in place is absolutely garbage.
