### ISSUE TITLE
OpenCommand spits out stacktrace under edge-case conditions.

### ISSUE THREAD

**Issue by MageFX** [codeHusky/HuskyCrates-Sponge#97]
Executing nokey. Fine ingame but not from console.

https://pastebin.com/aSvYfQ2K

**Comment by codeHusky** [comment]
Hi.
This only occurs from console because the console cannot open crates.
This error only occurs when the specified player to open the crate for does not exist and the command is run from console. In future versions there will be a more user friendly message for this.

If that doesn't resolve this issue, or isn't what should be happening, please provide more context. 
What command are you running specifically? What are you passing in for arguments? What are you trying to do?

**Comment by MageFX** [comment]
Im running
/hc o nokey aura MageFX from console
tried directly from console and using a command sign.

**Comment by codeHusky** [comment]
Seems to be a legitimate bug, investigating

**Comment by codeHusky** [comment]
Sponge and plugin versions please?
Also, does the command function properly in game when you try to open a crate view for another user?

**Comment by MageFX** [comment]
Command Fuctions as expected when running from Ingame only errors from console.

SpongeVersion 1.12.2-2838-7.1.8 STABLE
Husky 2.0.0RC2
UI 0.6.0PRE4

**Comment by MageFX** [comment]
Any luck on a fix?

**Comment by codeHusky** [comment]
This bug should be a programming challenge, jesus christ

**Comment by MageFX** [comment]
Issue still persists on -indev version

Error from opening a crate on player from console.
https://pastebin.com/GdMRc5Gn
